[package]
name = "spiders"
version = "0.1.0"
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.3"
tokio-core = "0.1"
select = "0.4.2"