[package]
name = "spiders"
version = "0.1.0"
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]

[dependencies]
failure = "0.1.1"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.3"
num_cpus = "1.8.0"
redis-async = "0.2.0"
select = "0.4.2"
tokio-core = "0.1"
